// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnQO3bMbDyzk614tjr6sg7CLfaqhO4gmQ',
    appId: '1:439040197507:web:932b9ec89845d9504d6cb6',
    messagingSenderId: '439040197507',
    projectId: 'staffconnect-2026',
    authDomain: 'staffconnect-2026.firebaseapp.com',
    storageBucket: 'staffconnect-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2AqGEa8dvaBtw-F3Rjvjo6H8NzguBwTw',
    appId: '1:439040197507:android:266d02213d7f84684d6cb6',
    messagingSenderId: '439040197507',
    projectId: 'staffconnect-2026',
    storageBucket: 'staffconnect-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoFav7KWfE1pL4iKyW2J8Sw91WjAdBK6s',
    appId: '1:439040197507:ios:01154f5c6941e83c4d6cb6',
    messagingSenderId: '439040197507',
    projectId: 'staffconnect-2026',
    storageBucket: 'staffconnect-2026.firebasestorage.app',
    iosBundleId: 'com.example.staffConnectDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoFav7KWfE1pL4iKyW2J8Sw91WjAdBK6s',
    appId: '1:439040197507:ios:01154f5c6941e83c4d6cb6',
    messagingSenderId: '439040197507',
    projectId: 'staffconnect-2026',
    storageBucket: 'staffconnect-2026.firebasestorage.app',
    iosBundleId: 'com.example.staffConnectDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnQO3bMbDyzk614tjr6sg7CLfaqhO4gmQ',
    appId: '1:439040197507:web:b1a9a078b044e3fc4d6cb6',
    messagingSenderId: '439040197507',
    projectId: 'staffconnect-2026',
    authDomain: 'staffconnect-2026.firebaseapp.com',
    storageBucket: 'staffconnect-2026.firebasestorage.app',
  );
}
